---
name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to my Dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: "ssh://dokku@panel.money-rise.com:22/mgz-backend"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
