---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to my Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'dokku@panel.money-rise.com:mgz-backend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
